loop_rate: 500.0 # the frequency at which to step sim in h
gravity: -9.81 # earth gravity in m/s^2
#max_torque: 100.0 # the maximal torque to apply to the robot joints in velocity mode

robots:
  rbcairos:
    - module: pybullet_ros.plugins.base_control
      class: BaseControl
    - module: pybullet_ros.plugins.joint_state_publisher
      class: JointStatePublisher
    - module: pybullet_ros.plugins.odometry
      class: Odom
      frame_name: robotbase_footprint
